"use client";

import { motion } from "framer-motion";
import SectionHeading from "./SectionHeading";
import { staggerContainer, staggerItem } from "@/utils/animations";
import { FolderGit2, ExternalLink } from "lucide-react";
import { FiGithub } from "react-icons/fi";

const projects = [
  {
    title: "CloudNotes",
    category: "Cloud Architecture",
    description: [
      "Engineered a direct-to-S3 image upload pipeline using SigV4 pre-signed PUT URLs generated by Lambda, bypassing API Gateway's 10 MB payload limits.",
      "Implemented defense-in-depth access control across 3 layers via Terraform IaC using CloudFront OAC, API Gateway HTTP v2 JWT authorizer, and least-privilege IAM execution roles.",
      "Built an immutable note version-history system that snapshots full note state to DynamoDB, capped at MAX_VERSIONS via Lambda env var, paired with a UUID-hex share-token system."
    ],
    tags: ["AWS Lambda", "DynamoDB", "Terraform", "CloudFront"],
    links: { github: "#contact" }
  },
  {
    title: "DalParkAid",
    category: "Full-Stack",
    description: [
      "Built a three-signal parking prediction engine fusing time/weather heuristics, crowdsourced reports weighted by exponential freshness decay, and a 42-day historical pattern model.",
      "Enforced submission data quality using haversine-formula proximity validation (30m geofence) and hardened cloud uploads via Firebase Storage security rules.",
      "Maintained cross-client consistency across four concurrent Firestore onSnapshot subscriptions using atomic read-modify-write transactions for community vote counts."
    ],
    tags: ["React Native", "Firebase", "Algorithms", "Expo"],
    links: { github: "#contact" }
  },
  {
    title: "Interactive World Map",
    category: "Frontend & Infrastructure",
    description: [
      "Enforced zero-trust S3 access via CloudFront Origin Access Control (OAC) with SigV4 signing — all public bucket ACLs blocked in Terraform.",
      "Implemented real-time GeoJSON layer re-styling on every keystroke with a 3-state style resolver computed in O(1) via JS Map lookups.",
      "Configured deterministic 30-color palette assignment with etag cache-busting in Terraform to ensure zero stale-asset serving on deployments."
    ],
    tags: ["Leaflet.js", "JavaScript", "Terraform", "CloudFront"],
    links: { github: "#contact", external: "https://d3rfup3qdmix7x.cloudfront.net/" }
  },
  {
    title: "SecureShare",
    category: "Cloud Security",
    description: [
      "Chained API Gateway's native JWT authorizer against Amazon Cognito with application-layer claim extraction, enforcing per-user data isolation in DynamoDB.",
      "Implemented defense-in-depth S3 access control by enabling all Block Public Access settings, AES256 server-side encryption, and 3600-second presigned URL expiry.",
      "Designed an ephemeral ECS Fargate janitor triggered by EventBridge scanning DynamoDB for expired entries and issuing targeted S3 deletions."
    ],
    tags: ["AWS Fargate", "Cognito", "S3", "EventBridge"],
    links: { github: "#contact", external: "#contact" }
  },
  {
    title: "DalOverflow",
    category: "Full-Stack / AI",
    description: [
      "Integrated Google Gemini 2.5 Flash API for AI-powered Q&A answer generation and multi-answer summarization with truncation-aware two-pass retry.",
      "Built layered stored-XSS defense using Python bleach with a regex pre-filter stripping injection; enforced at model creation and PUT edits via SQLAlchemy hooks.",
      "Designed a reusable JWT Flask decorator supporting dual API/session auth routing; applied optimistic concurrency control on question edits returning HTTP 409 Conflict."
    ],
    tags: ["Flask", "PostgreSQL", "Google Gemini API", "Security"],
    links: { github: "#contact", external: "#contact" }
  },
  {
    title: "Distributed DBMS Prototype",
    category: "Backend",
    description: [
      "Implemented a coordinator-worker distributed DBMS in Java supporting range-based row partitioning and vertical column partitioning across 2 worker nodes.",
      "Engineered distributed atomicity with 2PC-style coordination across all participant workers per DML operation using ReentrantLock-guarded execution.",
      "Built a custom multi-client TCP database server with wound-wait deadlock detection, per-session Thread dispatch, and a B+ tree index layer for range queries."
    ],
    tags: ["Java", "Distributed Systems", "Concurrency", "Sockets"],
    links: { github: "#contact" }
  }
];

export default function Projects() {
  return (
    <section id="projects" className="py-24 px-6 max-w-7xl mx-auto">
      <SectionHeading title="Featured Projects" />
      
      <motion.div 
        variants={staggerContainer}
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true, margin: "-50px" }}
        className="grid grid-cols-1 lg:grid-cols-2 gap-8 mt-12"
      >
        {projects.map((project, index) => (
          <motion.div 
            key={index}
            variants={staggerItem}
            className="group flex flex-col justify-between bg-dark-slate rounded-2xl p-8 hover:-translate-y-2 transition-all duration-300 hover:shadow-2xl hover:shadow-neon-teal/10 border border-slate-800 hover:border-neon-teal/30"
          >
            <div>
              <div className="flex justify-between items-center mb-6">
                <FolderGit2 className="text-electric-blue w-10 h-10" />
                <div className="flex gap-4">
                  {project.links.github && (
                    <a href={project.links.github} className="text-slate-400 hover:text-neon-teal transition-colors">
                      <FiGithub size={20} />
                    </a>
                  )}
                  {project.links.external && (
                    <a href={project.links.external} className="text-slate-400 hover:text-neon-teal transition-colors">
                      <ExternalLink size={20} />
                    </a>
                  )}
                </div>
              </div>
              
              <div className="text-neon-teal font-mono text-xs mb-2">{project.category}</div>
              <h3 className="text-2xl font-bold text-foreground mb-4 group-hover:text-electric-blue transition-colors">
                {project.title}
              </h3>
              
              <ul className="text-slate-400 text-sm leading-relaxed mb-8 space-y-3">
                {project.description.map((point, i) => (
                  <li key={i} className="flex gap-2">
                    <span className="text-neon-teal mt-1">▹</span>
                    <span>{point}</span>
                  </li>
                ))}
              </ul>
            </div>
            
            <ul className="flex flex-wrap gap-3 mt-auto pt-4 border-t border-slate-800">
              {project.tags.map((tag, i) => (
                <li key={i} className="text-xs font-mono text-slate-300 bg-deep-slate px-3 py-1 rounded-full border border-slate-800">
                  {tag}
                </li>
              ))}
            </ul>
          </motion.div>
        ))}
      </motion.div>
    </section>
  );
}
